#!/bin/bash

action_dir="/etc/vpsease"
script_dir="/root/vpsease"

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

get_os_name() {
	lsb_dist=""
	if [ -r /etc/os-release ]; then
		lsb_dist="$(. /etc/os-release && echo "$ID")"
	fi
	echo "$lsb_dist"
}

get_os_version() {
    lsb_dist=$( get_os_name )
    lsb_dist="$(echo "$lsb_dist" | tr '[:upper:]' '[:lower:]')"
    case "$lsb_dist" in
    
		ubuntu)
			if command_exists lsb_release; then
				dist_version="$(lsb_release --release --short)"
			fi
			if [ -z "$dist_version" ] && [ -r /etc/lsb-release ]; then
				dist_version="$(. /etc/lsb-release && echo "$DISTRIB_RELEASE")"
			fi
		;;

		debian|raspbian)
			dist_version="$(sed 's/\/.*//' /etc/debian_version | sed 's/\..*//')"
		;;

		centos|rhel)
			if [ -z "$dist_version" ] && [ -r /etc/os-release ]; then
				dist_version="$(. /etc/os-release && echo "$VERSION_ID")"
			fi
		;;

		*)
			if command_exists lsb_release; then
				dist_version="$(lsb_release --release | cut -f2)"
			fi
			if [ -z "$dist_version" ] && [ -r /etc/os-release ]; then
				dist_version="$(. /etc/os-release && echo "$VERSION_ID")"
			fi
		;;

	esac
    echo "$dist_version"
}

if [ "$(id -u)" -ne 0 ]; then
    echo "You are required to have root privileges for this command. Execute "sudo su" to gain root access."
    exit
fi

if [ -d "$action_dir" ]; then
    echo "Server/VPS is already set up with VPSEase"
    exit
fi

lsb_dist=$(get_os_name | tr '[:upper:]' '[:lower:]')
dist_version=$( get_os_version )

if [ -d "$script_dir" ]; then
    rm -rf "$script_dir"
fi

case "$lsb_dist$dist_version" in
    ubuntu24.04)
        if ! command_exists "git"; then
            sudo apt update 
            sudo apt install -y git
        fi
        mkdir -p $script_dir
        cd $script_dir
        git clone git@github.com:vpsease/vpsease.git .
        chmod -R +x $script_dir/*
        bash $script_dir/scripts/$lsb_dist/$dist_version/install
        ;;
    *)
        clear
        echo "Currently! VPSEase supports Ubuntu 24.04."
        exit
        ;;
esac