#!/bin/bash

. /etc/vpsease/lib/func

clear

PS3="$MSG_PROMPT"
options=("$MSG_UPDATE_VPSEASE" "$MSG_BACK")
name
select opt in "${options[@]}"; do
    case $opt in
        "$MSG_UPDATE_VPSEASE")
            /etc/vpsease/inc/vpsease_upgrade
            break
            ;;
        "$MSG_BACK")
            vpsease
            break
            ;;
        *)
            echo $MSG_INVALID_OPTION
            ;;
    esac
done