#!/bin/bash

script_dir="/root/vpsease"
action_dir="/etc/vpsease"

. $action_dir/lib/func



echo "$MSG_CHECK_VERSION"

NEW_VERSION=$(curl -s https://raw.githubusercontent.com/vpsease/vpsease/master/version)
CURRENT_VERSION=$(cat "$action_dir/version")

if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
    echo "${MSG_LATEST_VERSION//\$CURRENT_VERSION/$CURRENT_VERSION}"
else
    echo "${MSG_UPGRADING_VERSION//\$NEW_VERSION/$NEW_VERSION}"

    . $action_dir/.vpsease/vpsease

    if [ -d "$script_dir" ]; then
        rm -rf "$script_dir"
    fi

    mkdir -p $script_dir
    cd $script_dir
    git clone git@github.com:vpsease/vpsease.git .
    chmod -R +x $script_dir/*

    if [ "$STACK" == "LEMP" ]; then
        distro_dir="$script_dir/scripts/$DISTRO/$VERSION/"
        cp -r $distro_dir/* $action_dir/
        sudo cp $distro_dir/vpsease /usr/bin
        cp -r $script_dir/version $action_dir/version
        chmod -R +x $action_dir/*

        if [ -f "$action_dir/inc/update" ]; then
            bash "$action_dir/inc/update"
        fi

        NEW_VERSION=$(cat $action_dir/version)
        echo "${MSG_UPGRADE_COMPLETE//\$NEW_VERSION/$NEW_VERSION}"
    else
        echo "$MSG_UNKNOWN_STACK"
        exit;
    fi
fi
